name: Update Language Source

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Update Projects Source Json
        shell: pwsh
        run: iwr https://demo.foundryvtt.com/lang/en.json | % { if ($_.StatusCode -eq 200) { $_.Content > ./.github/en.json } }

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: ".github/en.json"
          branch: main
